""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" BASIC EDITING CONFIGURATION
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nonumber
set norelativenumber
set nocompatible
" allow unsaved background buffers and remember marks/undo for them
set hidden
" remember more commands and search history
set history=10000
set expandtab
set autoindent
set tabstop=2
set shiftwidth=2
set softtabstop=2
set laststatus=2
set showmatch
set matchtime=2
set incsearch
set hlsearch
" make searches case-sensitive only if they contain upper-case characters
set ignorecase smartcase
" highlight current line
set cursorline
set cmdheight=1
set switchbuf=useopen
set showtabline=2
set winwidth=79
set autoread
" This makes RVM work inside Vim. I have no idea why.
set shell=bash
" Prevent Vim from clobbering the scrollback buffer. See
" http://www.shallowsky.com/linux/noaltscreen.html
set t_ti= t_te=
" keep more context when scrolling off the end of a buffer
set scrolloff=3
" Store temporary files in a central spot
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
" allow backspacing over everything in insert mode
set backspace=indent,eol,start
" display incomplete commands
set showcmd
" Enable highlighting for syntax
syntax enable
" Enable file type detection.
" Use the default filetype settings, so that mail gets 'tw' set to 72,
" 'cindent' is on in C files, etc.
" Also load indent files, to automatically do language-dependent indenting.
filetype plugin indent on
" use emacs-style tab completion when selecting files, etc
set wildmode=longest,list
" make tab completion for files/buffers act like bash
set wildmenu
let mapleader=","
" Fix slow O inserts
set timeout timeoutlen=1000 ttimeoutlen=100

" Mode j, k one line also when wrapped
:nnoremap j gj
:nnoremap k gk

" Colorscheme
set t_Co=256
let g:seoul256_background = 233
let g:seoul256_light_background = 256
color seoul256-light

"hi Normal ctermbg=none

" Wordwrap
set wrap
set linebreak
" list disables linebreak
set nolist  

set mouse=a

" Convert word to upper case
imap <c-u> <esc>viwoU<esc>i
nmap <c-u> viwoU<esc>

" Mapps jump between splitscreens
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" Can't be bothered to understand ESC vs <c-c> in insert mode
imap <c-c> <esc>

" Mapps copy paste
map <leader>y "+y
map <leader>p "+p

" Mapps narrow/ wide splitscreen
map <Leader>j <C-w><
map <Leader>k <C-w>>

" hamlc syntax to haml
au BufRead,BufNewFile *.hamlc set ft=haml

" Move visual block
vnoremap J :m '>+1<CR>gv
vnoremap K :m '<-2<CR>gv

" Move to the previous buffer
nnoremap H :bprevious<CR>
" Move to the next buffer
nnoremap L :bnext<CR>
" Replace H and L
nnoremap zh H
nnoremap zl L
" AND/OR
nnoremap + H
nnoremap _ L

" set Y to duplicate line or selection
nmap Y yyp
vmap Y y`>pgv " Duplicates then regains selection.

" Edit vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" PLUGINS
" =======
"

 " RDF Notation 3 Syntax
"augroup filetypedetect
    "au BufNewFile,BufRead *.n3  setfiletype n3
    "au BufNewFile,BufRead *.ttl  setfiletype n3
"augroup END 

" Rainbowparanthesis
let g:rainbow#max_level = 16
let g:rainbow#pairs = [['(', ')'], ['[', ']']]
let g:rainbow#colors = {
\   'dark': [
\     ['yellow',  'orange1'     ],
\     ['green',   'yellow1'     ],
\     ['cyan',    'greenyellow' ],
\     ['magenta', 'green1'      ],
\     ['red',     'springgreen1'],
\     ['yellow',  'cyan1'       ],
\     ['green',   'slateblue1'  ],
\     ['cyan',    'magenta1'    ],
\     ['magenta', 'purple1'     ]
\   ],
\   'light': [
\     ['darkyellow',  'orangered3'    ],
\     ['darkgreen',   'orange2'       ],
\     ['blue',        'yellow3'       ],
\     ['darkmagenta', 'olivedrab4'    ],
\     ['red',         'green4'        ],
\     ['darkyellow',  'paleturquoise3'],
\     ['darkgreen',   'deepskyblue4'  ],
\     ['blue',        'darkslateblue' ],
\     ['darkmagenta', 'darkviolet'    ]
\   ]
\ }
autocmd VimEnter * RainbowParentheses

" GOYO
"autocmd User GoyoEnter Limelight
"autocmd User GoyoLeave Limelight!
nnoremap <Leader>G :Goyo<CR>

" Incsearch
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

" SingleCompile!
nmap <F9> :SCCompile<cr>
nmap <F10> :SCCompileRun<cr>

" Css colors
let g:cssColorVimDoNotMessMyUpdatetime = 1

" Python dictionary dictionary
let g:pydiction_location = '~/.vim/bundle/pydiction/complete-dict'

" YouCompleteMe
"let g:ycm_collect_identifiers_from_tags_files = 1
"let g:ycm_seed_identifiers_with_syntax = 1
"let g:ycm_extra_conf_vim_data = ['v:version']
"let g:ycm_autoclose_preview_window_after_completion = 1
"let g:ycm_autoclose_preview_window_after_insertion = 1

" NeoComplete
let g:neocomplete#enable_at_startup = 1
let g:acp_enableAtStartup = 0
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 2
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Enable heavy omni completion.
if !exists('g:neocomplcache_force_omni_patterns')
  let g:neocomplcache_force_omni_patterns = {}
endif
let g:neocomplcache_force_omni_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
let g:neocomplcache_force_omni_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'
let g:neocomplcache_force_omni_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'

" SuperTab like snippets behavior.
imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)"
\: pumvisible() ? "\<C-n>" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)"
\: "\<TAB>"

" For snippet_complete marker.
if has('conceal')
  set conceallevel=2 concealcursor=i
endif

" ctrlp
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_show_hidden = 1
let g:ctrlp_custom_ignore = '\v\.(exe|so|dll|o|pdf|jpg|png|tar|gz)$|\v[\/](build)$|\v[\/]\.(git|hg|svn)$'

" Markdown
let g:vim_markdown_folding_disabled=1

" Doxigen
let g:DoxygenToolkit_briefTag_pre=""

" NERDTree
let NERDTreeWinSize=31
let NERDTreeMinimalUI=1
"map <Leader>t :NERDTreeToggle<CR>
nmap <silent> <Leader>t :call g:WorkaroundNERDTreeToggle()<CR>

function! g:WorkaroundNERDTreeToggle()
  try | :NERDTreeToggle | catch | :NERDTree | endtry
endfunction

" loads closetag.vim
:au Filetype html,xml,xsl source ~/.vim/bundle/closetag.vim/plugin/closetag.vim

" FUNCTIONS
" =========

function! CompileTex()
  let filename = expand('%')
  if executable('pdflatex')
    exec '!pdflatex ' . filename
  endif
endfunction
nnoremap <leader>x :call CompileTex()<cr>

" Clear the search buffer when hitting return
function! MapCR()
  nnoremap <cr> :nohlsearch<cr>
endfunction
call MapCR()
nnoremap <leader><leader> <c-^>

" MULTIPURPOSE TAB KEY
" Indent if we're at the beginning of a line. Else, do completion.
"function! InsertTabWrapper()
  "let col = col('.') - 1
  "if !col || getline('.')[col - 1] !~ '\k'
    "return "\<tab>"
  "else
    "return "\<c-p>"
  "endif
"endfunction
"inoremap <tab> <c-r>=InsertTabWrapper()<cr>

" OPEN FILES IN DIRECTORY OF CURRENT FILE
cnoremap %% <C-R>=expand('%:h').'/'<cr>
map <leader>e :edit %%
map <leader>v :view %%

" Run scons after save c++ file
function! Scons()
  if executable('scons')
    exec '!scons'
  endif
endfunction
map <leader>b :call Scons()<cr>

" RENAME CURRENT FILE
function! RenameFile()
  let old_name = expand('%')
  let new_name = input('New file name: ', expand('%'), 'file')
  if new_name != '' && new_name != old_name
    exec ':saveas ' . new_name
    exec ':silent !rm ' . old_name
    redraw!
  endif
endfunction
map <leader>n :call RenameFile()<cr>

" RUN QMLSCENE FOR CURRENT FILE
function! Qmlscene()
  if executable('qmlscene')
    exec '!qmlscene ' . expand('%')
  endif
endfunction
map <leader>q :call Qmlscene()<cr>

" BUILD CURRENT QT PROJECT
function! BuildQtPro()
  exec '!cd ' . fnamemodify('*.pro', ':p:h')
  if executable('qmake') && executable('make')
    exec '!qmake'
    exec '!make'
  endif
endfunction
map <leader>w :call BuildQtPro()<cr>

autocmd BufRead,BufNewFile *.arb setfiletype ruby

" STRIP TRAILING WHITESPACES ON SAVE
function! <SID>StripTrailingWhitespaces()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfunction
autocmd FileType c,cpp,java,php,ruby,python,javascript,markdown,html autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

" NeoBundler for all the plugins
runtime neobundle.vim
